<?php
/*
define("SERVER","10.5.2.20");
define("USUARIO","grupo30");
define("PASS","invitado30");
define("BASE","grupo30");

define("SERVER","localhost");
define("USUARIO","gustavow");
define("PASS","pAbcar123");
define("BASE","ejer");
*/


define("SERVER","b3c1dnzjfajzfextbbcs-mysql.services.clever-cloud.com:3306");
define("USUARIO","ubtjuyglm1htsjy0");
define("PASS","S5mvHtQx7xjUvtPj6zbM");
define("BASE","b3c1dnzjfajzfextbbcs");

?>